<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php $posts = $this->getPosts() ?>
<?php if (count($posts) > 0): ?>
	<div class="block-content clearfix information">
			<ul id="<?php echo $this->getListId() ?>">
			<?php foreach($posts as $post): ?>
				<li class="item">
					<a href="<?php echo $post->getPermalink() ?>" title="<?php echo $this->htmlEscape($post->getPostTitle()) ?>"><?php echo $this->htmlEscape($post->getPostTitle()) ?> - <?php echo $this->htmlEscape($post->getPostDate()); ?></a>
				</li>
			<?php endforeach; ?>
			</ul>
	</div>
<?php endif; ?>